/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 16-Mar-2024 04:29:22
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 29
 * 稳定     : 是
 * 线性相位   : 是 (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\Matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 29;
const real32_T B[29] = {
  -0.001822523074,-0.001587929321,1.226008847e-18, 0.003697750857, 0.008075430058,
   0.008530221879,-4.273456581e-18, -0.01739769801, -0.03414586186, -0.03335915506,
  8.073562366e-18,  0.06763084233,   0.1522061825,   0.2229246944,   0.2504960895,
     0.2229246944,   0.1522061825,  0.06763084233,8.073562366e-18, -0.03335915506,
   -0.03414586186, -0.01739769801,-4.273456581e-18, 0.008530221879, 0.008075430058,
   0.003697750857,1.226008847e-18,-0.001587929321,-0.001822523074
};
